export const strings = {
  appName: 'JOKGER',
  common: {
    loading: 'Memuat…',
    retry: 'Coba lagi',
    cancel: 'Batal',
    close: 'Tutup',
    save: 'Simpan',
    signOut: 'Keluar',
    notConfigured: 'Koneksi Supabase belum dikonfigurasi.',
  },
  auth: {
    title: 'Masuk ke JOKGER',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    forgotPassword: 'Lupa kata sandi?',
    invalidCredentials: 'Email atau kata sandi salah.',
    required: 'Email dan kata sandi wajib diisi.',
    locked: 'Terlalu banyak percobaan. Coba lagi dalam {seconds} detik.',
    inactive: 'Akun ini tidak aktif. Hubungi super admin.',
    resetSent: 'Tautan reset kata sandi sudah dikirim ke email Anda.',
    resetFailed: 'Tautan reset kata sandi tidak dapat dikirim.',
  },
  authorization: {
    forbiddenTitle: 'Akses ditolak',
    forbiddenDescription: 'Peran akun Anda tidak memiliki akses ke halaman ini.',
    backToPos: 'Kembali ke POS',
    loginRequired: 'Silakan masuk untuk melanjutkan.',
  },
  shell: {
    shiftOpen: 'Shift terbuka',
    shiftClosed: 'Shift tertutup',
    online: 'Terhubung',
    offline: 'Tidak ada koneksi',
    pos: 'POS',
    shift: 'Shift',
    currentUser: 'Pengguna saat ini',
  },
  pos: {
    title: 'Kasir',
    loading: 'Menyiapkan POS…',
    noShift: 'Buka kasir sebelum membuat transaksi.',
    openShift: 'Buka kasir',
    cart: 'Keranjang',
    clearCart: 'Kosongkan',
    confirmClearCart: 'Semua item di keranjang akan dihapus.',
    cartEmpty: 'Keranjang masih kosong.',
    removeVoucher: 'Hapus voucher',
    voucherCode: 'Kode voucher',
    applyVoucher: 'Terapkan',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    service: 'Layanan',
    tax: 'PB1',
    rounding: 'Pembulatan',
    total: 'Total',
    openBill: 'Open bill',
    pay: 'Bayar',
    decreaseQuantity: 'Kurangi jumlah',
    increaseQuantity: 'Tambah jumlah',
    removeItem: 'Hapus item',
    modifierLimit: 'Pilihan maksimal untuk grup ini sudah terpenuhi.',
    modifierRequired: 'Pilih {group} sebelum menambahkan item.',
    modifiers: 'Pilih modifier',
    chooseAtLeast: 'Pilih minimal',
    itemNote: 'Catatan item',
    addItem: 'Tambahkan ke keranjang',
    paymentTitle: 'Pembayaran',
    amountDue: 'Tagihan',
    paymentMethod: 'Metode pembayaran',
    cash: 'Tunai',
    transfer: 'Transfer',
    ewallet: 'E-wallet',
    split: 'Split',
    cashReceived: 'Uang diterima',
    exactCash: 'Uang pas',
    change: 'Kembalian',
    paymentAccount: 'Rekening tujuan',
    chooseAccount: 'Pilih rekening',
    referenceNo: 'Nomor referensi',
    remaining: 'Sisa tagihan',
    amount: 'Nominal',
    addPaymentLine: 'Tambah metode pembayaran',
    finishPrint: 'Selesai & Cetak',
    sendVerification: 'Kirim untuk verifikasi',
    cashTooLow: 'Uang diterima belum mencukupi.',
    splitMismatch: 'Jumlah pembayaran split harus sama dengan tagihan.',
    searchMenu: 'Cari menu',
    allCategories: 'Semua',
    categories: 'Kategori menu',
    shortcutItem: 'Item nomor',
    noMenuResults: 'Menu tidak ditemukan.',
    unavailable: 'Habis',
    orderSuccess: 'Pesanan berhasil dibuat.',
    newOrder: 'Pesanan baru',
    viewOrders: 'Lihat pesanan',
    paymentError:
      'Pesanan tersimpan, tetapi pembayaran belum berhasil. Coba kirim pembayaran lagi.',
    connectionRequired: 'Koneksi diperlukan untuk membuat transaksi.',
    orderType: 'Tipe pesanan',
    takeaway: 'Bungkus',
    dineIn: 'Makan di tempat',
  },
  shift: {
    title: 'Shift kasir',
    invalidOpeningCash: 'Saldo awal harus berupa rupiah bulat positif atau nol.',
    invalidActualCash: 'Tunai aktual harus berupa rupiah bulat positif atau nol.',
    opened: 'Kasir berhasil dibuka.',
    closed: 'Kasir berhasil ditutup.',
    openBillsRemain: 'Masih ada {count} open bill yang harus ditutup atau dibatalkan.',
    openedAt: 'Waktu buka',
    openingCash: 'Saldo awal tunai',
    orderCount: 'Jumlah pesanan',
    noPayments: 'Belum ada pembayaran.',
    expectedCash: 'Tunai yang diharapkan',
    confirmCashTitle: 'Hitung tunai aktual',
    actualCash: 'Tunai aktual',
    cashExact: 'Pas',
    cashShort: 'Selisih kurang Rp {amount}',
    cashOver: 'Selisih lebih Rp {amount}',
    note: 'Catatan penutupan',
    closeTitle: 'Tutup kasir',
    openBills: 'Open bill aktif',
    nextStep: 'Lanjut hitung tunai',
    confirmClose: 'Konfirmasi tutup kasir',
    openTitle: 'Buka kasir',
    openDescription: 'Catat jumlah uang tunai yang tersedia di laci saat shift dimulai.',
    openButton: 'Buka shift',
  },
  orders: {
    title: 'Pesanan',
    all: 'Semua',
    new: 'Baru',
    processing: 'Diproses',
    ready: 'Menunggu diambil',
    cancelled: 'Dibatalkan',
    completed: 'Selesai',
    openBills: 'Open bill',
    empty: 'Belum ada pesanan pada filter ini.',
    process: 'Proses',
    markReady: 'Siap',
    complete: 'Selesaikan',
    cancel: 'Batalkan pesanan',
    cancelTitle: 'Batalkan pesanan?',
    cancelDescription: 'Stok akan dikembalikan. Alasan pembatalan wajib diisi.',
    cancelConfirm: 'Batalkan',
    itemCount: '{count} item',
    dineIn: 'Makan di tempat',
    takeaway: 'Bungkus',
    minutes: '{count} menit',
    overdue: 'Menunggu lebih dari 15 menit',
    refresh: 'Muat ulang',
    loading: 'Memuat pesanan…',
  },
  orderDetail: {
    title: 'Detail pesanan',
    items: 'Item pesanan',
    payments: 'Pembayaran',
    audit: 'Riwayat aktivitas',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    service: 'Layanan',
    tax: 'PB1',
    rounding: 'Pembulatan',
    total: 'Total',
    void: 'Void item',
    voidTitle: 'Void item pesanan?',
    voidDescription: 'Stok akan dikembalikan dan total pesanan dihitung ulang. Alasan wajib diisi.',
    verify: 'Setujui pembayaran',
    reject: 'Tolak pembayaran',
    rejectTitle: 'Tolak pembayaran?',
    rejectDescription:
      'Pembayaran ditolak dan kasir dapat mengirim pembayaran baru. Alasan wajib diisi.',
    proofMissing: 'Bukti belum dilampirkan.',
    proof: 'Bukti pembayaran',
    openProof: 'Buka bukti pembayaran',
    reason: 'Alasan',
    noAudit: 'Belum ada aktivitas.',
    noItems: 'Tidak ada item aktif.',
  },
  menu: {
    title: 'Menu',
    catalog: 'Katalog',
    categories: 'Kategori menu',
    items: 'Item menu',
    addItem: 'Tambah menu',
    edit: 'Ubah',
    name: 'Nama menu',
    category: 'Kategori',
    price: 'Harga',
    description: 'Deskripsi',
    active: 'Menu aktif',
    available: 'Tersedia',
    soldOut: 'Habis hari ini',
    newCategory: 'Nama kategori baru',
    addCategory: 'Tambah kategori',
    categoryRequired: 'Nama kategori wajib diisi.',
    invalidItem: 'Periksa kembali data menu dan harga.',
    deactivate: 'Nonaktifkan',
    deactivateConfirm: 'Nonaktifkan menu {name}? Riwayat penjualan tetap tersimpan.',
    moveUp: 'Pindah ke atas',
    moveDown: 'Pindah ke bawah',
    noItems: 'Belum ada menu pada kategori ini.',
  },
  inventory: {
    title: 'Inventory',
    items: 'Bahan baku',
    addItem: 'Tambah bahan',
    name: 'Nama bahan',
    unit: 'Satuan',
    minimum: 'Stok minimum',
    unitCost: 'Harga pokok per satuan',
    current: 'Stok saat ini',
    stockValue: 'Nilai stok',
    status: 'Status',
    safe: 'Aman',
    low: 'Menipis',
    out: 'Habis',
    purchase: 'Tambah pembelian',
    waste: 'Catat waste',
    movement: 'Pergerakan stok',
    movementInvalid: 'Masukkan jumlah pergerakan yang valid.',
    movementType: 'Jenis pergerakan',
    quantity: 'Jumlah',
    note: 'Catatan',
    saveMovement: 'Simpan pergerakan',
    insufficientStock: 'Stok tidak mencukupi untuk pergerakan ini.',
    movementsEmpty: 'Belum ada pergerakan stok.',
    opname: 'Stok opname',
    startOpname: 'Mulai stok opname',
    noItems: 'Belum ada bahan baku.',
    search: 'Cari bahan',
    all: 'Semua bahan',
    onlyLow: 'Hanya stok menipis',
  },
  vouchers: {
    title: 'Voucher',
    create: 'Buat voucher',
    edit: 'Ubah voucher',
    search: 'Cari kode voucher',
    code: 'Kode',
    name: 'Nama voucher',
    value: 'Nilai diskon',
    period: 'Periode',
    quota: 'Kuota terpakai',
    status: 'Status',
    actions: 'Aksi',
    active: 'Aktif',
    inactive: 'Nonaktif',
    deactivate: 'Nonaktifkan',
    deactivateConfirm: 'Voucher tidak dapat dihapus karena penggunaan tersimpan.',
    type: 'Jenis diskon',
    percent: 'Persentase',
    nominal: 'Nominal rupiah',
    minimum: 'Minimum belanja',
    maxDiscount: 'Maksimum potongan',
    startDate: 'Mulai berlaku',
    endDate: 'Berakhir',
    preview: 'Pratinjau belanja Rp 100.000',
    samplePurchase: 'Contoh transaksi',
    codeTaken: 'Kode voucher sudah digunakan.',
    invalid: 'Periksa kembali data voucher.',
  },
  stockOpname: {
    title: 'Stok opname',
    draft: 'Draft',
    finalized: 'Finalisasi',
    finalizedBanner: 'Stok opname sudah difinalisasi dan hanya dapat dibaca.',
    systemQty: 'Stok sistem',
    countedQty: 'Stok hitung',
    difference: 'Selisih',
    onlyDifferences: 'Hanya yang selisih',
    notCounted: 'Belum dihitung',
    saving: 'Menyimpan…',
    saved: 'Tersimpan',
    enterCount: 'Masukkan stok hitung',
    finalizeTitle: 'Finalisasi stok opname',
    finalizeDescription: 'Semua selisih akan dicatat ke ledger dan opname tidak dapat diubah.',
    typeFinalize: 'Ketik FINALISASI untuk melanjutkan',
    confirmFinalize: 'Finalisasi',
    countsIncomplete: 'Semua bahan harus dihitung sebelum finalisasi.',
    empty: 'Belum ada stok opname.',
  },
  openBill: {
    title: 'Open bill',
    table: 'Meja atau pelanggan',
    addItems: 'Tambahkan item',
    closeBill: 'Tutup bill',
    applyVoucher: 'Terapkan voucher ke bill',
    alreadyClosed: 'Bill ini sudah ditutup dan hanya dapat dibaca.',
    itemsAdded: 'Item berhasil ditambahkan ke bill.',
    voucherApplied: 'Voucher berhasil diterapkan ke bill.',
    billClosed: 'Bill berhasil ditutup.',
    noItems: 'Belum ada item pada bill ini.',
  },
  errors: {
    SHIFT_NOT_OPEN: 'Buka kasir sebelum membuat transaksi.',
    OPEN_BILL_REMAINS: 'Tutup atau batalkan open bill sebelum menutup kasir.',
    ORDER_NOT_FOUND: 'Pesanan tidak ditemukan.',
    ORDER_STATUS_TRANSITION_INVALID: 'Perubahan status pesanan tidak diizinkan.',
    PAYMENT_NOT_VERIFIED: 'Pembayaran harus terverifikasi sebelum pesanan selesai.',
    PAYMENT_TOTAL_MISMATCH: 'Jumlah pembayaran tidak sama dengan total tagihan.',
    VOUCHER_NOT_FOUND: 'Kode voucher tidak ditemukan.',
    VOUCHER_INACTIVE: 'Voucher sudah tidak aktif.',
    VOUCHER_EXPIRED: 'Voucher belum berlaku atau sudah kedaluwarsa.',
    VOUCHER_QUOTA_EXCEEDED: 'Kuota voucher sudah habis.',
    VOUCHER_MINIMUM_NOT_MET: 'Belanja belum memenuhi minimum voucher.',
    STOCK_INSUFFICIENT: 'Stok bahan tidak mencukupi.',
    BILL_CLOSED: 'Open bill sudah ditutup.',
    REASON_REQUIRED: 'Alasan wajib diisi untuk tindakan ini.',
    NOT_AUTHORIZED: 'Anda tidak memiliki izin untuk tindakan ini.',
    NETWORK_ERROR: 'Koneksi terputus. Periksa internet lalu coba lagi.',
    REQUEST_TIMEOUT: 'Koneksi lambat, coba lagi.',
    UNKNOWN: 'Terjadi kesalahan. Silakan coba lagi.',
  },
  sharedUi: {
    darkTheme: 'Aktifkan tema gelap',
    lightTheme: 'Aktifkan tema terang',
    processing: 'Memproses…',
    close: 'Tutup',
    closePanel: 'Tutup panel',
    closeNotification: 'Tutup notifikasi',
    clearSearch: 'Hapus pencarian',
    previousPage: 'Halaman sebelumnya',
    nextPage: 'Halaman berikutnya',
    pageNavigation: 'Navigasi halaman',
    dateFrom: 'Dari tanggal',
    dateTo: 'Sampai tanggal',
    reason: 'Alasan',
    rows: 'Baris',
    rowsOf: '{start}–{end} dari {total}',
    pageOf: 'Halaman {page} dari {total}',
    loadingData: 'Memuat data',
    saveState: 'Penyimpanan',
    filterOptions: 'Cari pilihan',
    selectAllRows: 'Pilih semua baris',
    selectRow: 'Pilih baris {id}',
    presets: {
      today: 'Hari ini',
      yesterday: 'Kemarin',
      sevenDays: '7 hari',
      month: 'Bulan ini',
    },
    status: {
      new: 'Baru',
      processing: 'Diproses',
      ready: 'Menunggu diambil',
      completed: 'Selesai',
      cancelled: 'Dibatalkan',
      pendingVerification: 'Menunggu verifikasi',
      verified: 'Terverifikasi',
      rejected: 'Ditolak',
      open: 'Terbuka',
      closed: 'Ditutup',
    },
  },
} as const;
