export const strings = {
  appName: 'JOKGER',
  common: {
    loading: 'Memuat…',
    retry: 'Coba lagi',
    cancel: 'Batal',
    close: 'Tutup',
    save: 'Simpan',
    signOut: 'Keluar',
    notConfigured: 'Koneksi Supabase belum dikonfigurasi.',
  },
  auth: {
    title: 'Masuk ke JOKGER',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    forgotPassword: 'Lupa kata sandi?',
    invalidCredentials: 'Email atau kata sandi salah.',
    required: 'Email dan kata sandi wajib diisi.',
    locked: 'Terlalu banyak percobaan. Coba lagi dalam {seconds} detik.',
    inactive: 'Akun ini tidak aktif. Hubungi super admin.',
    resetSent: 'Tautan reset kata sandi sudah dikirim ke email Anda.',
    resetFailed: 'Tautan reset kata sandi tidak dapat dikirim.',
  },
  authorization: {
    forbiddenTitle: 'Akses ditolak',
    forbiddenDescription:
      'Peran akun Anda tidak memiliki akses ke halaman ini.',
    backToPos: 'Kembali ke POS',
    loginRequired: 'Silakan masuk untuk melanjutkan.',
  },
  shell: {
    shiftOpen: 'Shift terbuka',
    shiftClosed: 'Shift tertutup',
    online: 'Terhubung',
    offline: 'Tidak ada koneksi',
    pos: 'POS',
    shift: 'Shift',
    currentUser: 'Pengguna saat ini',
  },
  pos: {
    title: 'Kasir',
    loading: 'Menyiapkan POS…',
    noShift: 'Buka kasir sebelum membuat transaksi.',
    openShift: 'Buka kasir',
  },
  errors: {
    SHIFT_NOT_OPEN: 'Buka kasir sebelum membuat transaksi.',
    OPEN_BILL_REMAINS: 'Tutup atau batalkan open bill sebelum menutup kasir.',
    ORDER_NOT_FOUND: 'Pesanan tidak ditemukan.',
    ORDER_STATUS_TRANSITION_INVALID:
      'Perubahan status pesanan tidak diizinkan.',
    PAYMENT_NOT_VERIFIED:
      'Pembayaran harus terverifikasi sebelum pesanan selesai.',
    PAYMENT_TOTAL_MISMATCH:
      'Jumlah pembayaran tidak sama dengan total tagihan.',
    VOUCHER_NOT_FOUND: 'Kode voucher tidak ditemukan.',
    VOUCHER_INACTIVE: 'Voucher sudah tidak aktif.',
    VOUCHER_EXPIRED: 'Voucher belum berlaku atau sudah kedaluwarsa.',
    VOUCHER_QUOTA_EXCEEDED: 'Kuota voucher sudah habis.',
    VOUCHER_MINIMUM_NOT_MET: 'Belanja belum memenuhi minimum voucher.',
    STOCK_INSUFFICIENT: 'Stok bahan tidak mencukupi.',
    BILL_CLOSED: 'Open bill sudah ditutup.',
    REASON_REQUIRED: 'Alasan wajib diisi untuk tindakan ini.',
    NOT_AUTHORIZED: 'Anda tidak memiliki izin untuk tindakan ini.',
    NETWORK_ERROR: 'Koneksi terputus. Periksa internet lalu coba lagi.',
    REQUEST_TIMEOUT: 'Koneksi lambat, coba lagi.',
    UNKNOWN: 'Terjadi kesalahan. Silakan coba lagi.',
  },
} as const;
