export const strings = {
  appName: 'JOKGER',
  common: {
    loading: 'Memuat…',
    retry: 'Coba lagi',
    cancel: 'Batal',
    close: 'Tutup',
    save: 'Simpan',
    signOut: 'Keluar',
    notConfigured: 'Koneksi Supabase belum dikonfigurasi.',
  },
  auth: {
    title: 'Masuk ke JOKGER',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    forgotPassword: 'Lupa kata sandi?',
    invalidCredentials: 'Email atau kata sandi salah.',
    required: 'Email dan kata sandi wajib diisi.',
    locked: 'Terlalu banyak percobaan. Coba lagi dalam {seconds} detik.',
    inactive: 'Akun ini tidak aktif. Hubungi super admin.',
    resetSent: 'Tautan reset kata sandi sudah dikirim ke email Anda.',
    resetFailed: 'Tautan reset kata sandi tidak dapat dikirim.',
  },
  authorization: {
    forbiddenTitle: 'Akses ditolak',
    forbiddenDescription: 'Peran akun Anda tidak memiliki akses ke halaman ini.',
    backToPos: 'Kembali ke POS',
    loginRequired: 'Silakan masuk untuk melanjutkan.',
  },
  shell: {
    shiftOpen: 'Kasir terbuka',
    shiftClosed: 'Kasir tertutup',
    online: 'Terhubung',
    offline: 'Tidak ada koneksi',
    pos: 'POS',
    orders: 'Pesanan',
    history: 'Riwayat',
    shift: 'Shift',
    menu: 'Menu',
    inventory: 'Inventaris',
    vouchers: 'Voucher',
    payments: 'Pembayaran',
    reports: 'Laporan',
    settings: 'Pengaturan',
    audit: 'Audit',
    currentUser: 'Pengguna saat ini',
  },
  pos: {
    title: 'Kasir',
    loading: 'Menyiapkan POS…',
    noShift: 'Buka kasir sebelum membuat transaksi.',
    openShift: 'Buka kasir',
    cart: 'Keranjang',
    clearCart: 'Kosongkan',
    confirmClearCart: 'Semua item di keranjang akan dihapus.',
    cartEmpty: 'Keranjang masih kosong.',
    removeVoucher: 'Hapus voucher',
    voucherCode: 'Kode voucher',
    applyVoucher: 'Terapkan',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    service: 'Layanan',
    tax: 'PB1',
    rounding: 'Pembulatan',
    total: 'Total',
    openBill: 'Open bill',
    pay: 'Bayar',
    decreaseQuantity: 'Kurangi jumlah',
    increaseQuantity: 'Tambah jumlah',
    removeItem: 'Hapus item',
    modifierLimit: 'Pilihan maksimal untuk grup ini sudah terpenuhi.',
    modifierRequired: 'Pilih {group} sebelum menambahkan item.',
    modifiers: 'Pilih modifier',
    chooseAtLeast: 'Pilih minimal',
    itemNote: 'Catatan item',
    addItem: 'Tambahkan ke keranjang',
    paymentTitle: 'Pembayaran',
    amountDue: 'Tagihan',
    paymentMethod: 'Metode pembayaran',
    cash: 'Tunai',
    transfer: 'Transfer',
    ewallet: 'E-wallet',
    split: 'Split',
    cashReceived: 'Uang diterima',
    exactCash: 'Uang pas',
    change: 'Kembalian',
    paymentAccount: 'Rekening tujuan',
    chooseAccount: 'Pilih rekening',
    referenceNo: 'Nomor referensi',
    paymentProof: 'Bukti pembayaran (opsional; JPG, PNG, WEBP; maks. 5 MB)',
    proofImage: 'Bukti pembayaran harus berupa JPG, PNG, atau WEBP.',
    proofTooLarge: 'Ukuran bukti pembayaran maksimal 5 MB.',
    remaining: 'Sisa tagihan',
    amount: 'Nominal',
    addPaymentLine: 'Tambah metode pembayaran',
    finishPrint: 'Selesai & Cetak',
    sendVerification: 'Kirim untuk verifikasi',
    cashTooLow: 'Uang diterima belum mencukupi.',
    splitMismatch: 'Jumlah pembayaran split harus sama dengan tagihan.',
    searchMenu: 'Cari menu',
    allCategories: 'Semua',
    categories: 'Kategori menu',
    shortcutItem: 'Item nomor',
    noMenuResults: 'Menu tidak ditemukan.',
    unavailable: 'Habis',
    orderSuccess: 'Pesanan berhasil dibuat.',
    newOrder: 'Pesanan baru',
    viewOrders: 'Lihat pesanan',
    paymentError:
      'Pesanan tersimpan, tetapi pembayaran belum berhasil. Coba kirim pembayaran lagi.',
    connectionRequired: 'Koneksi diperlukan untuk membuat transaksi.',
    orderType: 'Tipe pesanan',
    takeaway: 'Bungkus',
    dineIn: 'Makan di tempat',
  },
  shift: {
    title: 'Shift kasir',
    invalidOpeningCash: 'Saldo awal harus berupa rupiah bulat positif atau nol.',
    invalidActualCash: 'Tunai aktual harus berupa rupiah bulat positif atau nol.',
    opened: 'Kasir berhasil dibuka.',
    closed: 'Kasir berhasil ditutup.',
    openBillsRemain: 'Masih ada {count} open bill yang harus ditutup atau dibatalkan.',
    openedAt: 'Waktu buka',
    openingCash: 'Saldo awal tunai',
    orderCount: 'Jumlah pesanan',
    noPayments: 'Belum ada pembayaran.',
    expectedCash: 'Tunai yang diharapkan',
    confirmCashTitle: 'Hitung tunai aktual',
    actualCash: 'Tunai aktual',
    cashExact: 'Pas',
    cashShort: 'Selisih kurang Rp {amount}',
    cashOver: 'Selisih lebih Rp {amount}',
    note: 'Catatan penutupan',
    closeTitle: 'Tutup kasir',
    openBills: 'Open bill aktif',
    nextStep: 'Lanjut hitung tunai',
    confirmClose: 'Konfirmasi tutup kasir',
    openTitle: 'Buka kasir',
    openDescription: 'Catat jumlah uang tunai yang tersedia di laci saat shift dimulai.',
    openButton: 'Buka shift',
  },
  orders: {
    title: 'Pesanan',
    all: 'Semua',
    new: 'Baru',
    processing: 'Diproses',
    ready: 'Menunggu diambil',
    cancelled: 'Dibatalkan',
    completed: 'Selesai',
    openBills: 'Open bill',
    empty: 'Belum ada pesanan pada filter ini.',
    process: 'Proses',
    markReady: 'Siap',
    complete: 'Selesaikan',
    cancel: 'Batalkan pesanan',
    cancelTitle: 'Batalkan pesanan?',
    cancelDescription: 'Stok akan dikembalikan. Alasan pembatalan wajib diisi.',
    cancelConfirm: 'Batalkan',
    itemCount: '{count} item',
    dineIn: 'Makan di tempat',
    takeaway: 'Bungkus',
    minutes: '{count} menit',
    overdue: 'Menunggu lebih dari 15 menit',
    refresh: 'Muat ulang',
    loading: 'Memuat pesanan…',
  },
  orderDetail: {
    title: 'Detail pesanan',
    reprint: 'Cetak ulang struk',
    items: 'Item pesanan',
    payments: 'Pembayaran',
    audit: 'Riwayat aktivitas',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    service: 'Layanan',
    tax: 'PB1',
    rounding: 'Pembulatan',
    total: 'Total',
    void: 'Void item',
    voidTitle: 'Void item pesanan?',
    voidDescription: 'Stok akan dikembalikan dan total pesanan dihitung ulang. Alasan wajib diisi.',
    verify: 'Setujui pembayaran',
    reject: 'Tolak pembayaran',
    rejectTitle: 'Tolak pembayaran?',
    rejectDescription:
      'Pembayaran ditolak dan kasir dapat mengirim pembayaran baru. Alasan wajib diisi.',
    proofMissing: 'Bukti belum dilampirkan.',
    proof: 'Bukti pembayaran',
    openProof: 'Buka bukti pembayaran',
    reason: 'Alasan',
    noAudit: 'Belum ada aktivitas.',
    noItems: 'Tidak ada item aktif.',
  },
  menu: {
    title: 'Menu',
    catalog: 'Katalog',
    categories: 'Kategori menu',
    items: 'Item menu',
    addItem: 'Tambah menu',
    edit: 'Ubah',
    name: 'Nama menu',
    category: 'Kategori',
    price: 'Harga',
    description: 'Deskripsi',
    active: 'Menu aktif',
    available: 'Tersedia',
    soldOut: 'Habis hari ini',
    newCategory: 'Nama kategori baru',
    addCategory: 'Tambah kategori',
    categoryRequired: 'Nama kategori wajib diisi.',
    invalidItem: 'Periksa kembali data menu dan harga.',
    deactivate: 'Nonaktifkan',
    deactivateConfirm: 'Nonaktifkan menu {name}? Riwayat penjualan tetap tersimpan.',
    moveUp: 'Pindah ke atas',
    moveDown: 'Pindah ke bawah',
    noItems: 'Belum ada menu pada kategori ini.',
  },
  inventory: {
    title: 'Inventory',
    items: 'Bahan baku',
    addItem: 'Tambah bahan',
    name: 'Nama bahan',
    unit: 'Satuan',
    minimum: 'Stok minimum',
    unitCost: 'Harga pokok per satuan',
    current: 'Stok saat ini',
    stockValue: 'Nilai stok',
    status: 'Status',
    safe: 'Aman',
    low: 'Menipis',
    out: 'Habis',
    purchase: 'Tambah pembelian',
    waste: 'Catat waste',
    movement: 'Pergerakan stok',
    movementInvalid: 'Masukkan jumlah pergerakan yang valid.',
    movementType: 'Jenis pergerakan',
    quantity: 'Jumlah',
    note: 'Catatan',
    saveMovement: 'Simpan pergerakan',
    insufficientStock: 'Stok tidak mencukupi untuk pergerakan ini.',
    movementsEmpty: 'Belum ada pergerakan stok.',
    opname: 'Stok opname',
    startOpname: 'Mulai stok opname',
    noItems: 'Belum ada bahan baku.',
    search: 'Cari bahan',
    all: 'Semua bahan',
    onlyLow: 'Hanya stok menipis',
  },
  vouchers: {
    title: 'Voucher',
    create: 'Buat voucher',
    edit: 'Ubah voucher',
    search: 'Cari kode voucher',
    code: 'Kode',
    name: 'Nama voucher',
    value: 'Nilai diskon',
    period: 'Periode',
    quota: 'Kuota terpakai',
    status: 'Status',
    actions: 'Aksi',
    active: 'Aktif',
    inactive: 'Nonaktif',
    deactivate: 'Nonaktifkan',
    deactivateConfirm: 'Voucher tidak dapat dihapus karena penggunaan tersimpan.',
    type: 'Jenis diskon',
    percent: 'Persentase',
    nominal: 'Nominal rupiah',
    minimum: 'Minimum belanja',
    maxDiscount: 'Maksimum potongan',
    startDate: 'Mulai berlaku',
    endDate: 'Berakhir',
    preview: 'Pratinjau belanja Rp 100.000',
    samplePurchase: 'Contoh transaksi',
    codeTaken: 'Kode voucher sudah digunakan.',
    invalid: 'Periksa kembali data voucher.',
  },
  stockOpname: {
    title: 'Stok opname',
    draft: 'Draft',
    finalized: 'Finalisasi',
    finalizedBanner: 'Stok opname sudah difinalisasi dan hanya dapat dibaca.',
    systemQty: 'Stok sistem',
    countedQty: 'Stok hitung',
    difference: 'Selisih',
    onlyDifferences: 'Hanya yang selisih',
    notCounted: 'Belum dihitung',
    saving: 'Menyimpan…',
    saved: 'Tersimpan',
    enterCount: 'Masukkan stok hitung',
    finalizeTitle: 'Finalisasi stok opname',
    finalizeDescription: 'Semua selisih akan dicatat ke ledger dan opname tidak dapat diubah.',
    typeFinalize: 'Ketik FINALISASI untuk melanjutkan',
    confirmFinalize: 'Finalisasi',
    countsIncomplete: 'Semua bahan harus dihitung sebelum finalisasi.',
    empty: 'Belum ada stok opname.',
  },
  openBill: {
    title: 'Open bill',
    table: 'Meja atau pelanggan',
    addItems: 'Tambahkan item',
    closeBill: 'Tutup bill',
    applyVoucher: 'Terapkan voucher ke bill',
    alreadyClosed: 'Bill ini sudah ditutup dan hanya dapat dibaca.',
    itemsAdded: 'Item berhasil ditambahkan ke bill.',
    voucherApplied: 'Voucher berhasil diterapkan ke bill.',
    billClosed: 'Bill berhasil ditutup.',
    noItems: 'Belum ada item pada bill ini.',
  },
  history: {
    title: 'Riwayat transaksi',
    subtitle: 'Filter, cari, dan ekspor riwayat penjualan.',
    searchPlaceholder: 'Cari nomor pesanan…',
    filterStatus: 'Status',
    filterMethod: 'Metode bayar',
    filterType: 'Tipe pesanan',
    filterDate: 'Tanggal',
    clearFilters: 'Hapus filter',
    showFilters: 'Tampilkan filter',
    hideFilters: 'Sembunyikan filter',
    totalTransactions: 'Total transaksi',
    totalSales: 'Total penjualan',
    avgTransaction: 'Rata-rata transaksi',
    colOrderNo: 'Nomor pesanan',
    colDate: 'Tanggal',
    colType: 'Tipe',
    colItems: 'Item',
    colMethod: 'Metode',
    colTotal: 'Total',
    colStatus: 'Status',
    colCashier: 'Kasir',
    colItem: 'Item',
    colQty: 'Jumlah',
    colUnitPrice: 'Harga satuan',
    colModifiers: 'Modifier',
    colLineTotal: 'Total baris',
    colProvider: 'Provider',
    colRef: 'No. referensi',
    colAmount: 'Nominal',
    emptyTitle: 'Belum ada transaksi',
    emptyDescription: 'Transaksi akan muncul di sini setelah pesanan pertama selesai.',
    detailTitle: 'Detail transaksi',
    orderInfo: 'Informasi pesanan',
    items: 'Item pesanan',
    payments: 'Pembayaran',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    service: 'Layanan',
    tax: 'PB1',
    rounding: 'Pembulatan',
    grandTotal: 'Total',
    typeDineIn: 'Makan di tempat',
    typeTakeaway: 'Bungkus',
    exporting: 'Mengekspor…',
  },
  payments: {
    title: 'Rekening pembayaran',
    subtitle: 'Kelola rekening bank dan e-wallet untuk pembayaran transfer.',
    addAccount: 'Tambah rekening',
    editAccount: 'Edit rekening',
    deactivateAccount: 'Nonaktifkan',
    deactivateAccountConfirm:
      'Nonaktifkan rekening ini? Riwayat pembayaran tetap menyimpan rekening yang pernah digunakan.',
    accountDeactivated: 'Rekening dinonaktifkan',
    colProvider: 'Penyedia',
    colAccountName: 'Nama pemilik',
    colAccountNo: 'Nomor rekening',
    colMethod: 'Metode',
    colStatus: 'Status',
    active: 'Aktif',
    inactive: 'Nonaktif',
    emptyTitle: 'Belum ada rekening',
    emptyDescription: 'Tambahkan rekening bank atau e-wallet untuk pembayaran transfer.',
    verificationTitle: 'Verifikasi pembayaran',
    verificationSubtitle: 'Tinjau dan verifikasi bukti pembayaran transfer.',
    proofTitle: 'Bukti pembayaran',
    noProof: 'Belum ada bukti terlampir',
    detailTitle: 'Detail pembayaran',
    colOrderNo: 'Nomor pesanan',
    colAmount: 'Nominal',
    colRef: 'No. referensi',
    colCashier: 'Kasir',
    colDate: 'Tanggal',
    approve: 'Setujui',
    reject: 'Tolak',
    rejectTitle: 'Tolak pembayaran',
    rejectDescription: 'Masukkan alasan penolakan. Kasir akan diberitahu.',
    rejectReason: 'Alasan penolakan',
    rejectPlaceholder: 'Contoh: Nominal tidak sesuai, bukti tidak jelas, nomor referensi salah',
    rejectConfirm: 'Tolak',
    verified: 'Terverifikasi',
    rejected: 'Ditolak',
    exported: 'Laporan diekspor',
    exportFailed: 'Gagal mengekspor',
    exporting: 'Mengekspor…',
  },
  reports: {
    title: 'Laporan penjualan',
    subtitle: 'Ringkasan dan analisis performa penjualan.',
    exportCSV: 'Ekspor CSV',
    exporting: 'Mengekspor…',
    totalSales: 'Total penjualan',
    totalTransactions: 'Total transaksi',
    avgTransaction: 'Rata-rata transaksi',
    totalDiscount: 'Total diskon',
    totalService: 'Total layanan',
    totalTax: 'Total pajak',
    totalVoid: 'Total void',
    colDate: 'Tanggal',
    colTotalSales: 'Total penjualan',
    colTransactions: 'Transaksi',
    colAvgTransaction: 'Rata-rata transaksi',
    colHour: 'Jam',
    colCategory: 'Kategori',
    colQty: 'Kuantitas',
    colItem: 'Item',
    colMethod: 'Metode',
    colVoucherCode: 'Kode voucher',
    colVoucherName: 'Nama voucher',
    colUsageCount: 'Jumlah pemakaian',
    colTotalDiscount: 'Total diskon',
    emptyTitle: 'Tidak ada data',
    emptyDescription: 'Tidak ada data untuk rentang tanggal ini.',
  },
  settings: {
    title: 'Pengaturan',
    subtitle: 'Kelola pengaturan toko, branding, staff, dan printer.',
    general: 'Umum',
    branding: 'Branding',
    staff: 'Staff',
    printer: 'Printer',
    brandingSubtitle: 'Kustomisasi tampilan toko: logo dan warna.',
    storeName: 'Nama toko',
    address: 'Alamat',
    phone: 'Telepon',
    taxPercent: 'Persentase pajak (PB1)',
    servicePercent: 'Persentase layanan',
    roundingRule: 'Aturan pembulatan',
    receiptHeader: 'Header struk',
    receiptFooter: 'Footer struk',
    paperWidth: 'Lebar kertas struk',
    requireVerification: 'Wajib verifikasi pembayaran sebelum selesai',
    openTime: 'Jam buka',
    closeTime: 'Jam tutup',
    primaryColor: 'Warna utama',
    accentColor: 'Warna aksen',
    fontFamily: 'Font',
    logo: 'Logo',
    uploadLogo: 'Unggah logo',
    logoUploaded: 'Logo berhasil diunggah',
    invalidImage: 'File harus berupa gambar',
    imageTooLarge: 'Ukuran maksimal 1 MB',
    saved: 'Pengaturan disimpan',
    staffTitle: 'Manajemen staff',
    staffSubtitle: 'Kelola akun staff: tambah, edit peran, aktifkan/nonaktifkan.',
    addStaff: 'Tambah staff',
    editStaff: 'Edit staff',
    email: 'Email',
    fullName: 'Nama lengkap',
    role: 'Peran',
    password: 'Password',
    colName: 'Nama',
    colEmail: 'Email',
    colRole: 'Peran',
    colStatus: 'Status',
    colCreated: 'Dibuat',
    emptyStaffTitle: 'Belum ada staff',
    emptyStaffDescription: 'Tambahkan staff pertama untuk memulai.',
    staffCreated: 'Staff berhasil ditambahkan',
    staffCreateInvalid: 'Data staff tidak valid. Periksa email, nama, dan kata sandi.',
    staffCreateUnauthorized: 'Sesi Anda berakhir. Silakan masuk kembali.',
    staffCreateForbidden: 'Hanya super admin yang dapat membuat akun staff.',
    staffCreateMethodNotAllowed: 'Permintaan pembuatan staff tidak didukung.',
    staffCreateFailed: 'Staff gagal dibuat. Silakan coba lagi.',
    activated: 'Staff diaktifkan',
    deactivated: 'Staff dinonaktifkan',
    activateConfirm: 'Aktifkan staff ini?',
    deactivateConfirm: 'Nonaktifkan staff ini? Staff tidak bisa login.',
    roleChangeConfirm: 'Ubah peran staff ini?',
    roleUpdated: 'Peran diperbarui',
    confirm: 'Konfirmasi',
    printerTitle: 'Pengaturan printer',
    printerSubtitle: 'Hubungkan printer Bluetooth termal untuk cetak struk.',
    connection: 'Koneksi',
    preferences: 'Preferensi',
    help: 'Bantuan',
    connectPrinter: 'Hubungkan printer',
    connecting: 'Menghubungkan…',
    connected: 'Tersambung',
    disconnected: 'Terputus',
    testPrint: 'Cetak uji',
    paperWidthLabel: 'Lebar kertas',
    defaultCopies: 'Salinan default',
    printerNotConfigured: 'Printer belum dikonfigurasi',
    noDevice: 'Tidak ada printer yang tersambung',
    bluetoothNotSupported:
      'Browser ini tidak mendukung Web Bluetooth. Gunakan Chrome/Edge di Android, Windows, atau macOS.',
    learnMore: 'Pelajari lebih lanjut',
    help1: 'Printer termal Bluetooth dengan dukungan ESC/POS diperlukan.',
    help2: 'Hanya didukung di Chrome/Edge di Android, Windows, macOS, dan ChromeOS.',
    help3: 'iOS/Safari tidak mendukung Web Bluetooth. Gunakan cetak via browser (AirPrint).',
    help4: 'Pastikan printer dalam mode pairing dan dekat dengan perangkat.',
    testPrintSent: 'Uji cetak dikirim',
    printFailed: 'Gagal mencetak',
    printViaBrowser: 'Cetak via browser',
    printQueueTitle: 'Antrian cetak lokal',
    printQueueEmpty: 'Tidak ada struk dalam antrian.',
    retryPrint: 'Coba cetak lagi',
    removeQueuedPrint: 'Hapus dari antrian',
    printQueueSaved: 'Dialog cetak gagal dibuka. Struk disimpan di antrian lokal.',
    printQueueLoadFailed: 'Antrian cetak lokal tidak dapat dibaca.',
    connectionFailed: 'Koneksi gagal',
    notConnected: 'Printer tidak tersambung',
  },
  audit: {
    title: 'Audit log',
    subtitle: 'Riwayat aktivitas sistem untuk keperluan audit dan keamanan.',
    searchPlaceholder: 'Cari aksi…',
    filterEntity: 'Entitas',
    filterDate: 'Tanggal',
    allEntities: 'Semua entitas',
    colId: 'ID',
    colTime: 'Waktu',
    colActor: 'Aktor',
    colAction: 'Aksi',
    colEntity: 'Entitas',
    colEntityId: 'ID Entitas',
    detailTitle: 'Detail audit log',
    detailInfo: 'Informasi detail',
    payload: 'Payload',
    system: 'Sistem',
    emptyTitle: 'Belum ada log audit',
    emptyDescription: 'Log audit akan muncul di sini setelah ada aktivitas sistem.',
    exportCSV: 'Ekspor CSV',
    exporting: 'Mengekspor…',
    exported: 'Audit log diekspor',
    exportFailed: 'Gagal mengekspor',
    clearFilters: 'Hapus filter',
    showFilters: 'Tampilkan filter',
    hideFilters: 'Sembunyikan filter',
  },
  printer: {
    bluetoothNotSupported:
      'Browser ini tidak mendukung Web Bluetooth. Gunakan Chrome/Edge di Android, Windows, atau macOS.',
    learnMore: 'Pelajari lebih lanjut',
    connecting: 'Menghubungkan…',
    connected: 'Tersambung',
    disconnected: 'Terputus',
    noDevice: 'Tidak ada printer yang tersambung',
    connectPrinter: 'Hubungkan printer',
    testPrint: 'Cetak uji',
    testPrintSent: 'Uji cetak dikirim',
    printFailed: 'Gagal mencetak',
    connectionFailed: 'Koneksi gagal',
    paperWidth: 'Lebar kertas',
    defaultCopies: 'Salinan default',
    notConnected: 'Printer tidak tersambung',
    help1: 'Printer termal Bluetooth dengan dukungan ESC/POS diperlukan.',
    help2: 'Hanya didukung di Chrome/Edge di Android, Windows, macOS, dan ChromeOS.',
    help3: 'iOS/Safari tidak mendukung Web Bluetooth. Gunakan cetak via browser (AirPrint).',
    help4: 'Pastikan printer dalam mode pairing dan dekat dengan perangkat.',
  },
  errors: {
    SHIFT_NOT_OPEN: 'Buka kasir sebelum membuat transaksi.',
    OPEN_BILL_REMAINS: 'Tutup atau batalkan open bill sebelum menutup kasir.',
    ORDER_NOT_FOUND: 'Pesanan tidak ditemukan.',
    ORDER_STATUS_TRANSITION_INVALID: 'Perubahan status pesanan tidak diizinkan.',
    PAYMENT_NOT_VERIFIED: 'Pembayaran harus terverifikasi sebelum pesanan selesai.',
    PAYMENT_TOTAL_MISMATCH: 'Jumlah pembayaran tidak sama dengan total tagihan.',
    VOUCHER_NOT_FOUND: 'Kode voucher tidak ditemukan.',
    VOUCHER_INACTIVE: 'Voucher sudah tidak aktif.',
    VOUCHER_EXPIRED: 'Voucher belum berlaku atau sudah kedaluwarsa.',
    VOUCHER_QUOTA_EXCEEDED: 'Kuota voucher sudah habis.',
    VOUCHER_MINIMUM_NOT_MET: 'Belanja belum memenuhi minimum voucher.',
    STOCK_INSUFFICIENT: 'Stok bahan tidak mencukupi.',
    BILL_CLOSED: 'Open bill sudah ditutup.',
    REASON_REQUIRED: 'Alasan wajib diisi untuk tindakan ini.',
    NOT_AUTHORIZED: 'Anda tidak memiliki izin untuk tindakan ini.',
    STAFF_CREATE_INVALID: 'Data staff tidak valid. Periksa email, nama, dan kata sandi.',
    STAFF_CREATE_UNAUTHORIZED: 'Sesi Anda berakhir. Silakan masuk kembali.',
    STAFF_CREATE_FORBIDDEN: 'Hanya super admin yang dapat membuat akun staff.',
    STAFF_CREATE_METHOD_NOT_ALLOWED: 'Permintaan pembuatan staff tidak didukung.',
    STAFF_CREATE_FAILED: 'Staff gagal dibuat. Silakan coba lagi.',
    PAYMENT_ACCOUNT_NOT_FOUND: 'Rekening pembayaran tidak ditemukan.',
    PAYMENT_PROOF_TOO_LARGE: 'Ukuran bukti pembayaran maksimal 5 MB.',
    PAYMENT_PROOF_TYPE_INVALID: 'Bukti pembayaran harus berupa JPG, PNG, atau WEBP.',
    NETWORK_ERROR: 'Koneksi terputus. Periksa internet lalu coba lagi.',
    REQUEST_TIMEOUT: 'Koneksi lambat, coba lagi.',
    UNKNOWN: 'Terjadi kesalahan. Silakan coba lagi.',
  },
  sharedUi: {
    darkTheme: 'Aktifkan tema gelap',
    lightTheme: 'Aktifkan tema terang',
    processing: 'Memproses…',
    close: 'Tutup',
    closePanel: 'Tutup panel',
    closeNotification: 'Tutup notifikasi',
    clearSearch: 'Hapus pencarian',
    previousPage: 'Halaman sebelumnya',
    nextPage: 'Halaman berikutnya',
    pageNavigation: 'Navigasi halaman',
    dateFrom: 'Dari tanggal',
    dateTo: 'Sampai tanggal',
    reason: 'Alasan',
    rows: 'Baris',
    rowsOf: '{start}–{end} dari {total}',
    pageOf: 'Halaman {page} dari {total}',
    loadingData: 'Memuat data',
    saveState: 'Penyimpanan',
    filterOptions: 'Cari pilihan',
    selectAllRows: 'Pilih semua baris',
    selectRow: 'Pilih baris {id}',
    presets: {
      today: 'Hari ini',
      yesterday: 'Kemarin',
      sevenDays: '7 hari',
      month: 'Bulan ini',
    },
    status: {
      new: 'Baru',
      processing: 'Diproses',
      ready: 'Menunggu diambil',
      completed: 'Selesai',
      cancelled: 'Dibatalkan',
      pendingVerification: 'Menunggu verifikasi',
      verified: 'Terverifikasi',
      rejected: 'Ditolak',
      open: 'Terbuka',
      closed: 'Ditutup',
    },
  },
} as const;
